-- Phase 3 hard cleanup: remove legacy local-identity columns from user_credential.
-- Run this manually in a maintenance window after deploying the Phase-3 code.
-- Adjust/dropping FK names may be required depending on your existing schema.

-- 1) Drop foreign key to role if present (name may differ by environment).
-- Example generated by Hibernate is often fk_*; check with:
-- SHOW CREATE TABLE user_credential;
-- ALTER TABLE user_credential DROP FOREIGN KEY <your_fk_name>;

-- 2) Drop legacy columns that are now Keycloak-owned.
ALTER TABLE user_credential
    DROP COLUMN IF EXISTS first_name,
    DROP COLUMN IF EXISTS last_name,
    DROP COLUMN IF EXISTS email,
    DROP COLUMN IF EXISTS phone,
    DROP COLUMN IF EXISTS password,
    DROP COLUMN IF EXISTS role_id,
    DROP COLUMN IF EXISTS email_verified;

-- 3) Keep and enforce keycloak linkage.
ALTER TABLE user_credential
    MODIFY COLUMN keycloak_user_id VARCHAR(64) NOT NULL;

-- 4) Optional: ensure uniqueness/index if missing.
-- CREATE UNIQUE INDEX ux_user_credential_keycloak_user_id
--     ON user_credential (keycloak_user_id);
